### ISSUE TITLE
What is the purpose of empty repo?

### ISSUE THREAD

**Issue by zangrafx** [spacekick/space-preconfigured-esformatter#1]
xD

**Comment by mcharytoniuk** [comment]
Placeholder for https://github.com/millermedeiros/esformatter config that is going to allow painless transition between eslint-config-goreutils (https://github.com/goreutils/eslint-config-goreutils) and space-preconfigured-eslint.

**Comment by mcharytoniuk** [comment]
It's not emty now. ;)
